CREATE DATABASE agenda DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE agenda;

CREATE TABLE actividades(
    idUsr INT NOT NULL DEFAULT 0
    ,fecha VARCHAR(10) NOT NULL DEFAULT ''
    ,horaI VARCHAR(6) NOT NULL DEFAULT ''
    ,horaF VARCHAR(6) NOT NULL DEFAULT ''
    ,actividad VARCHAR(250) NOT NULL DEFAULT ''
)ENGINE=MyISAM CHARSET=utf8 COLLATE utf8_general_ci;
